name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  FRONTEND_IMAGE: govindr458/frontend
  BACKEND_IMAGE: govindr458/backend

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t frontend ./frontend
          docker tag frontend:latest ${{ env.FRONTEND_IMAGE }}:latest
          docker push ${{ env.FRONTEND_IMAGE }}:latest

      - name: Build and push backend image
        run: |
          docker build -t backend ./backend
          docker tag backend:latest ${{ env.BACKEND_IMAGE }}:latest
          docker push ${{ env.BACKEND_IMAGE }}:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f manifests/
